    name: Deploy ASP.NET Razor Pages App to IIS

    on:
      push:
        branches: [ master ]  # or your deployment branch

    jobs:
      build-and-deploy:
        runs-on: windows-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'  # or whatever version you use

        - name: Restore and Build
          run: |
            dotnet restore ./TestCICD/TestCICD.csproj
            dotnet publish ./TestCICD/TestCICD.csproj -c Release -o published --verbosity detailed
        - name: Deploy to IIS using msdeploy
          run: |
            "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" ^
              -source:contentPath="published" ^
              -dest:contentPath="Default Web Site/TestCICD",computerName="https://${{ secrets.IIS_HOST }}:8172/msdeploy.axd?site=Default Web Site",username="${{ secrets.IIS_USERNAME }}",password="${{ secrets.IIS_PASSWORD }}",authType="Basic" ^
              -verb:sync ^
              -allowUntrusted
