    name: Deploy ASP.NET Razor Pages App to IIS

    on:
      push:
        branches: [ master ]  # or your deployment branch

    jobs:
      build-and-deploy:
        runs-on: windows-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'  # or whatever version you use

        - name: Restore and Build
          run: |
            dotnet restore ./TestCICD/TestCICD.csproj
            dotnet publish ./TestCICD/TestCICD.csproj -c Release -o published --verbosity detailed

        - name: Deploy via WinRM
          uses: gsoft-actions/iis-deploy@v1
          with:
            source-path: published
            computer-name: http://20.204.113.67:5985/wsman
            username: ${{ secrets.IIS_USERNAME }}
            password: ${{ secrets.IIS_PASSWORD }}
            site-name: "TestCICD"
            app-path: "Default Web Site\\TestCICD"
